# Generated by Django 4.2.5 on 2023-09-07 19:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=10)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="verified_by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
                "db_table": "authors",
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("content", ckeditor.fields.RichTextField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("viewsCount", models.IntegerField(default=0)),
                ("thumbnail", models.ImageField(upload_to="Blog/Images")),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                ("like_count", models.IntegerField(default=0)),
                (
                    "author_id",
                    models.ForeignKey(
                        db_column="author_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="blog.author",
                    ),
                ),
            ],
            options={
                "db_table": "blogs",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Cateogory",
                "verbose_name_plural": "Cateogories",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="CategoryBlog",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "blog_id",
                    models.ForeignKey(
                        db_column="blog_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="blog.blog",
                    ),
                ),
                (
                    "category_id",
                    models.ForeignKey(
                        db_column="category_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="blog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Cateogories",
                "db_table": "blog_categories",
            },
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField()),
                ("is_edited", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_id",
                    models.ForeignKey(
                        db_column="parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="blog.blogcomment",
                    ),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        db_column="post_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="blog.blog",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "blog_comments",
                "ordering": ["-created_on"],
            },
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ManyToManyField(
                through="blog.CategoryBlog", to="blog.category"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="uploaded_by",
            field=models.ForeignKey(
                db_column="uploaded_by",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
