# Generated by Django 4.2.5 on 2023-09-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="viewsCount",
        ),
        migrations.AddField(
            model_name="blog",
            name="view_count",
            field=models.IntegerField(db_column="view_count", default=0),
        ),
    ]
