# Generated by Django 4.2.5 on 2023-09-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_blog_viewscount_blog_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.ManyToManyField(
                related_name="blog_category",
                through="blog.CategoryBlog",
                to="blog.category",
            ),
        ),
        migrations.AlterField(
            model_name="categoryblog",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
