# Generated by Django 4.2.5 on 2023-09-09 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blog_category_alter_categoryblog_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="uploaded_on",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
