# Generated by Django 4.2.5 on 2023-09-09 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_blog_uploaded_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="uploaded_on",
        ),
    ]
