# Generated by Django 4.2.5 on 2023-09-11 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0005_remove_blog_uploaded_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="about_you",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="author",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_id",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="author",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                db_column="verified_by",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="verified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
