# Generated by Django 4.2.5 on 2023-09-12 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_author_about_you_author_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryblog",
            name="blog_id",
            field=models.ForeignKey(
                db_column="blog_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.blog",
            ),
        ),
    ]
