# Generated by Django 4.2.5 on 2023-09-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_categoryblog_blog_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("full_name", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "contact",
                "ordering": ["-created_on"],
            },
        ),
    ]
