# Generated by Django 4.2.5 on 2023-09-12 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="exipired",
            new_name="expired",
        ),
    ]
